server:
  port: 8080
zuul:
  routes:
    movies:
      path: /api/movies/**
      url: http://localhost:8081/api/movies
    showtimes:
      path: /api/showtime/**
      url: http://localhost:8082/api/showtime
    bookings:
      path: /api/booking/**
      url: http://localhost:8083/api/booking