CREATE TABLE IF NOT EXISTS booking(
  id INTEGER(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  movie_id INTEGER(10) NOT NULL,
  showtime_id INTEGER(10) NOT NULL,
  booking_no VARCHAR(100) NOT NULL,
  username VARCHAR(75) NOT NULL,
  createDate DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS ticket(
  id INTEGER(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  seat_no VARCHAR(100) NOT NULL,
  booking_id INTEGER(100) NOT NULL
);